### PR TITLE
Fix NaturalDate bug

### LINKED ISSUE #210: [PE-D] Confusion in placing order using natural dates
Placing an order using natural date leads to much confusion.

For example, today is a Friday, and suppose I place an order for next Friday using natural date (i.e. Friday). From a logical point of view, if a user inputs a time that is in the past (e.g. Friday 10AM when order is placed at 3PM), the order should be scheduled for the following Friday instead of today.

However, because of allowing past orders to be added, as well as the open interpretation on usage of natural dates, it will lead to many bugs and confusion. A solution could be to give clearer instructions about natural dates, or remove it completely.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lzan98/ped#8

### PR DESCRIPTION
**Pull request by punnyhuimin**
Natural date now takes into account the time instead of purely looking at the natural day given to it. This means that if I inputted Wednesday 00:30, and the current time is 00:58, it references the Wednesday from next week instead.

Closes #210

### CODE REVIEW

File: src/main/java/seedu/address/model/order/DateChecker.java [hunk 1]
```diff
@@ -103,6 +90,8 @@ public static String parsePotentialNaturalDate(String input) {
             String date = inputSplit[0];
             String time = inputSplit[1];
             dateToCheck = date;
+            timeToCheck = time;
+            isTimeBeforeCurrentTime = inputTimeBeforeCurrentTimeChecker();
             naturalDateCheck();
```
Comment (declanleeler) [inline src/main/java/seedu/address/model/order/DateChecker.java:95]: violation of SLAP.
you might want to create another method to hide the details of the processing of the class variables before naturalDateCheck()

**Review by declanleeler — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/order/DateChecker.java (hunk 1 above)
Comment (punnyhuimin) [reply src/main/java/seedu/address/model/order/DateChecker.java:92]: Updated this. Good catch!

**Review by declanleeler — APPROVED** [review]
LGTM
